name: Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: nicolasbolt/github-templates/.github/workflows/node-build.yml@main
    with:
      node-version: '20'

  # test:
  #   needs: build
  #   uses: nicolasbolt/github-templates/.github/workflows/node-test.yml@main
  #   with:
  #     node-version: '20'
  #     test-command: 'npm test'

  deploy:
    needs: build  # Change to 'test' if you enable the test job
    uses: nicolasbolt/github-templates/.github/workflows/digital-ocean-deploy.yml@main
    with:
      node-version: '20'
      source-path: 'dist/'
      build-command: 'npm run build'
    secrets:
      DO_HOST: ${{ secrets.DO_HOST }}
      DO_USERNAME: ${{ secrets.DO_USERNAME }}
      DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
      DO_TARGET_PATH: ${{ secrets.DO_TARGET_PATH }}